### ISSUE TITLE
VS 2019 - Don't work with <Multiple Startup Projects>

### ISSUE THREAD

**Issue by GetoXs** [Wakusei/BuildStartProject#1]
I found issue.
Steps:

1. Select single project to start
1. Press "Build only start project"
1. VS: Build one project
1. Add another project to start in Solution properties
1. Press "Build only start project" -> Build one project
1. VS: Build one project - **Wrong, should at least build two projs**

**Comment by Wakusei** [comment]
I'll try to support that.

**Comment by Wakusei** [comment]
It's supported now on the latest version.
